backend:
  name: github
  repo: FFXIVPocketGuide/DevFFXIVPocketGuide
  branch: master
  base_url: https://us-central1-thinking-window-255219.cloudfunctions.net
  auth_endpoint: /ffxiv-pg-oauth/auth

publish_mode: editorial_workflow

media_folder: "assets/img"

# COMMON ATTACK FIELDS
field_attack_name: &field_attack_name
  label: "Attack Name"
  name: "title"
  widget: "string"

field_roles: &field_roles
  label: "Roles"
  name: "roles"
  widget: "select"
  multiple: true
  options: ["Tank", "Healer", "Melee DPS", "Ranged DPS", "Everyone"]
  required: false

field_tags: &field_tags
  label: "Tags"
  name: "tags"
  widget: "select"
  multiple: true
  options: ["Cone AoE", "Circular AoE", "Puddle AoE", "Donut AoE", "Column AoE", "Area AoE", "Point Blank AoE", "Raid Wide AoE", "Proximity AoE", "Cross AoE", "Figure 8 AoE", "Knockback", "Cleave", "Buff", "Debuff", "Tankbuster", "Stack", "Spread", "Tether", "Stun", "Mechanic", "Animation", "Spawn", "Ultimate", "Active Time Maneuver", "Marker"]
  required: false

field_dutyActions: &field_dutyActions
  label: "Duty Actions"
  name: "dutyActions"
  widget: "list"
  field: {label: "Duty Action Name", name: "action", widget: "string", required: false}

field_notes: &field_notes
  label: "Notes"
  name: "notes"
  widget: "list"
  field: {label: "Note Text", name: "note", widget: "text", required: false}

field_related_phases: &field_related_phases
  label: "Related Phases"
  name: "phases"
  widget: "list"
  field: {name: "phase", widget: "number", valueType: "int"}

common_attack_fields: &common_attack_fields
  - *field_attack_name
  - *field_roles
  - *field_tags
  - *field_dutyActions
  - *field_notes

fields_template: &common_fields
  - label: "Expansion"
    name: "categories"
    widget: "select"
    options: 
      - {label: "Shadowbringers", value: "shb"}
      - {label: "Stormblood", value: "sb"}
      - {label: "Heavensward", value: "hw"}
      - {label: "A Realm Reborn", value: "arr"}
    hint: "The expansion to which the duty belongs. Used by front-end for categorizing the Guide."
  - {label: "Patch Number", name: "patchNumber", valueType: "float", widget: "number"}
  - {label: "Patch Name", name: "patchName", widget: "string"}
  - {label: "Title", name: "title", widget: "string"}
  - {label: "Slug", name: "slug", widget: "string"}
  - {label: "Difficulty", name: "difficulty", widget: "select", options: ["Normal", "Hard", "Extreme", "Savage", "Ultimate"]}
  - {label: "Player Level", name: "plvl", valueType: "int", widget: "number"}
  - {label: "Item Level", name: "ilvl", valueType: "int", widget: "number"}
  - {label: "Description", name: "description", widget: "text", required: false}
  - label: "Images"
    name: "image"
    widget: "object"
    fields:
      - {label: "Primary Banner Image", name: "url", widget: "image", allowMultiple: false}
      - {label: "Thumbnail Image", name: "urlSmall", widget: "image", allowMultiple: false}
    required: false
  - {label: "Terms", name: "terms", widget: "list", field: {label: Term, name: term, widget: string}, required: false}
  - {label: "Orchestrion Roll", name: "orchestrion", required: false, widget: "string"}
  - {label: "Minion(s)", name: "minion", required: false, widget: "string"}
  - {label: "Triple Triad Cards", name: "triple-triad", required: false, widget: "list", field: {label: "Card Name", name: "card-name", widget: "string"}}
  - {label: "Instance Type", name: "instanceType", widget: "select", options: ["dungeon", "trial", "raid"], required: false}
  - {label: "MTQ Capture Video", name: "mtqvid", widget: "string", required: false}
  - label: "Beginning Duty Mechanic"
    name: "mechanics"
    required: false
    widget: "list"
    fields:
      - {label: "Name", name: "title", widget: "string"}
      - label: "Mechanics"
        name: "steps"
        widget: "list"
        fields:
          - {label: "Note Number", name: "step", widget: "number", valueType: "int", required: false}
          - label: "Mechanic Notes"
            name: "notes"
            widget: "list"
            field: {label: "Mechanic Note", name: "note", widget: "text", required: false}
  - label: "Bosses"
    name: "bosses"
    widget: "list"
    fields:
      - {label: "Boss Name", name: "title", widget: "string"}
      - label: "Phases"
        name: "sequence"
        widget: "list"
        fields:
          - {label: "Phase Number", name: "phase", widget: "number", valueType: "int"}
          - label: "Alert"
            name: "alerts"
            widget: "list"
            field: {label: "Alert Text", name: "alert", widget: "text", required: false}
          - label: "Mechanics"
            name: "mechanics"
            widget: "list"
            fields: 
              - {label: "Mechanic Title", name: "title", widget: "string"}
              - label: "Mechanic Notes"
                name: "notes"
                widget: "list"
                field: {label: "Mechanic Note", name: "note", widget: "text", required: false}
          - label: "Attack Sequence"
            name: "attacks"
            widget: "list"
            fields: 
              - {label: "Attack Name", name: "attack", widget: "string", required: false}
              - {label: "Duty Action", name: "dutyActions", required: false, widget: "boolean"}
      - label: "Boss Attacks"
        name: "attacks"
        widget: "list"
        types:
          - label: "Regular Attack"
            name: "regular"
            widget: object
            fields:
              - *field_attack_name
              - *field_roles
              - *field_tags
              - *field_dutyActions
              - *field_notes
              - *field_related_phases
          - label: "Combo Attack"
            name: "combo"
            widget: object
            fields:
              - {label: "Attack Name", name: "title", widget: "string"}
              - *field_related_phases
              - label: "Sub-Attacks"
                name: "combo"
                widget: list
                fields:
                  *common_attack_fields
          - label: "Variation Attack"
            name: "variation"
            widget: object
            fields:
              - {label: "Attack Name", name: "title", widget: "string"}
              - *field_related_phases
              - label: "Sub-Attacks"
                name: "variation"
                widget: list
                fields:
                  *common_attack_fields
  # Hidden fields
  - {label: "Layout", name: "layout", widget: "hidden", default: "guide_post"}
  - {label: "Date", name: "date", widget: "hidden", default: "{{year}}-{{month}}-{{day}}"}
  - {label: "Order", name: "order", widget: "hidden", default: "{{plvl}}{{ilvl}}"}

collections:
  - name: "shb"
    label: "Shadowbringers"
    delete: false
    label_singular: "Guide"
    folder: "_posts/shb"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{patchNumber}}-{{fields.slug}}"
    summary: "{{title}} -- {{year}}/{{month}}/{{day}}"
    fields:
      *common_fields

  - name: "sb"
    label: "Stormblood"
    delete: false
    label_singular: "Guide"
    folder: "_posts/sb"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{patchNumber}}-{{fields.slug}}"
    summary: "{{title}} -- {{year}}/{{month}}/{{day}}"
    fields:
      *common_fields

  - name: "hw"
    label: "Heavensward"
    delete: false
    label_singular: "Guide"
    folder: "_posts/hw"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{patchNumber}}-{{fields.slug}}"
    summary: "{{title}} -- {{year}}/{{month}}/{{day}}"
    fields: 
      *common_fields

  - name: "arr"
    label: "A Realm Reborn"
    delete: false
    label_singular: "Guide"
    folder: "_posts/arr"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{patchNumber}}-{{fields.slug}}"
    summary: "{{title}} -- {{year}}/{{month}}/{{day}}"
    fields: 
      *common_fields
